trigger:
- main  # or your desired branch

pool:
  vmImage: ubuntu-latest

variables:
  vm_host: var.api_host
  vm_user: var.api_user
  vm_key: var.api_priv_key

stages:
- stage: Deploy
  jobs:
  - job: DeployToVM
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'Home-api-svc'
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: '**'
        targetFolder: '/home/azureuser/construction_manage_api'

    - task: SSH@0
      name: DockerDeploy
      inputs:
        sshEndpoint: 'Home-api-svc'
        runOptions: inline
        inline: |
          cd /home/azureuser/homeapi-src

          echo ">>> Building Docker image..."
                docker build -t homeapi .

          echo ">>> Stopping old container (if running)..."
                docker stop backend || true
                docker rm backend || true

          echo ">>> Running new container..."
                docker run -d --name backend -p 80:8000 homeapi