trigger:
- main  # or your desired branch

pool:
  vmImage: ubuntu-latest

variables:
  - group: backend-home-api

stages:
- stage: Deploy
  jobs:
  - job: DeployToVM
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'Home-api-svc'
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        contents: '**'
        targetFolder: '/home/azureuser/construction_manage_api'


    - task: SSH@0
      name: Env
      inputs:
        sshEndpoint: 'Home-api-svc'
        runOptions: inline
        inline: |
           sudo echo "Creating .env file..."
           sudo echo "OPENAI_API_KEY=$(API_KEY)" >> .env

    - task: SSH@0
      name: DockerDeploy
      inputs:
        sshEndpoint: 'Home-api-svc'
        runOptions: 'script'
        scriptpath: './home/azureuser/construction_manage_api/docker-deploy.sh'